// Realistic demo data for the Citizen Complaint Portal.
// Ages (daysAgo) are deliberately varied so the priority-scoring formula
// (upvotes * 2 + daysSinceCreated) produces a spread across LOW/MEDIUM/HIGH/CRITICAL.

const officer = {
  name: 'Officer Imran Qureshi',
  email: 'officer@civicportal.gov',
  password: 'Officer@123',
  role: 'officer',
};

const citizens = [
  { name: 'Ayesha Khan', email: 'ayesha@example.com', password: 'Citizen@123', role: 'citizen' },
  { name: 'Bilal Ahmed', email: 'bilal@example.com', password: 'Citizen@123', role: 'citizen' },
  { name: 'Sara Malik', email: 'sara@example.com', password: 'Citizen@123', role: 'citizen' },
  { name: 'Hamza Sheikh', email: 'hamza@example.com', password: 'Citizen@123', role: 'citizen' },
  { name: 'Fatima Raza', email: 'fatima@example.com', password: 'Citizen@123', role: 'citizen' },
];

// citizenIndex refers to the citizens array above (order preserved on insert).
// upvoterIndexes are indexes into the citizens array (excluding the author, ideally).
const complaintTemplates = [
  {
    title: 'Large pothole near main market',
    description:
      'A deep pothole has formed right outside the main market entrance, causing traffic slowdowns and damage to vehicle tires. It gets worse whenever it rains.',
    category: 'Road',
    area: 'Gulshan-e-Iqbal',
    citizenIndex: 0,
    daysAgo: 18,
    upvoterIndexes: [1, 2, 3, 4],
    status: 'pending',
  },
  {
    title: 'Damaged road near school',
    description:
      'The road leading to the government primary school has large cracks and exposed gravel, which is dangerous for children walking to school.',
    category: 'Road',
    area: 'Gulshan-e-Iqbal',
    citizenIndex: 1,
    daysAgo: 25,
    upvoterIndexes: [0, 2],
    status: 'pending',
  },
  {
    title: 'Broken pavement outside community center',
    description: 'Uneven and broken pavement tiles outside the community center are a tripping hazard, especially for elderly residents.',
    category: 'Road',
    area: 'Clifton',
    citizenIndex: 2,
    daysAgo: 4,
    upvoterIndexes: [0],
    status: 'pending',
  },
  {
    title: 'Garbage collection delayed',
    description:
      'Garbage has not been collected from our street for over a week. Bins are overflowing and it is starting to smell and attract stray animals.',
    category: 'Garbage',
    area: 'North Nazimabad',
    citizenIndex: 2,
    daysAgo: 10,
    upvoterIndexes: [0, 1, 3],
    status: 'in-progress',
    officerRemark: 'Team assigned. Truck rerouted for pickup by Friday.',
  },
  {
    title: 'Overflowing garbage bins in park',
    description: 'The public park bins have not been emptied in days and waste is spilling onto the walking paths.',
    category: 'Garbage',
    area: 'Clifton',
    citizenIndex: 3,
    daysAgo: 2,
    upvoterIndexes: [],
    status: 'pending',
  },
  {
    title: 'Illegal dumping near canal',
    description: 'Construction debris is being illegally dumped near the canal bank, blocking water flow and creating an eyesore.',
    category: 'Garbage',
    area: 'Malir',
    citizenIndex: 4,
    daysAgo: 32,
    upvoterIndexes: [0, 1, 2, 3],
    status: 'pending',
  },
  {
    title: 'Water supply interruption',
    description:
      'Our block has had no piped water supply for three days. Residents are having to buy water tankers at their own expense.',
    category: 'Water',
    area: 'Korangi',
    citizenIndex: 3,
    daysAgo: 6,
    upvoterIndexes: [0, 1, 2, 4],
    status: 'in-progress',
    officerRemark: 'Valve repair crew dispatched. Estimated restoration in 48 hours.',
  },
  {
    title: 'Low water pressure in apartment block',
    description: 'Water pressure has dropped significantly over the past month, making it difficult to fill overhead tanks.',
    category: 'Water',
    area: 'North Nazimabad',
    citizenIndex: 4,
    daysAgo: 15,
    upvoterIndexes: [1],
    status: 'pending',
  },
  {
    title: 'Sewage leak flooding street',
    description: 'A broken sewage line is flooding the street with wastewater, creating a serious health hazard for nearby residents.',
    category: 'Water',
    area: 'Malir',
    citizenIndex: 0,
    daysAgo: 3,
    upvoterIndexes: [1, 2, 3, 4],
    status: 'pending',
  },
  {
    title: 'Streetlight not working',
    description: 'Three consecutive streetlights on the main avenue have been out for two weeks, making the area unsafe at night.',
    category: 'Electricity',
    area: 'Gulshan-e-Iqbal',
    citizenIndex: 1,
    daysAgo: 20,
    upvoterIndexes: [0, 2, 3],
    status: 'resolved',
    officerRemark: 'Faulty transformer replaced and all three streetlights restored.',
    feedback: { rating: 5, comment: 'Fixed quickly, thank you!' },
  },
  {
    title: 'Frequent power outages',
    description: 'Our neighborhood experiences unscheduled power cuts almost daily, lasting 2-3 hours each time.',
    category: 'Electricity',
    area: 'Korangi',
    citizenIndex: 2,
    daysAgo: 9,
    upvoterIndexes: [0, 3, 4],
    status: 'pending',
  },
  {
    title: 'Exposed live wire near bus stop',
    description: 'A live electrical wire is hanging dangerously low near the bus stop, posing a serious safety risk to commuters.',
    category: 'Electricity',
    area: 'Clifton',
    citizenIndex: 3,
    daysAgo: 1,
    upvoterIndexes: [0, 1, 2, 4],
    status: 'pending',
  },
  {
    title: 'Transformer sparking at night',
    description: 'The neighborhood transformer has been sparking intermittently at night, alarming nearby residents.',
    category: 'Electricity',
    area: 'North Nazimabad',
    citizenIndex: 4,
    daysAgo: 27,
    upvoterIndexes: [0, 1, 2, 3],
    status: 'in-progress',
    officerRemark: 'Utility company notified. Inspection scheduled.',
  },
  {
    title: 'Stray dogs near playground',
    description: 'A pack of stray dogs has been gathering near the children\'s playground, worrying parents in the area.',
    category: 'Other',
    area: 'Malir',
    citizenIndex: 0,
    daysAgo: 7,
    upvoterIndexes: [2, 3],
    status: 'pending',
  },
  {
    title: 'Fallen tree blocking footpath',
    description: 'A large tree fell during last week\'s storm and is still blocking the footpath, forcing pedestrians onto the road.',
    category: 'Other',
    area: 'Gulshan-e-Iqbal',
    citizenIndex: 1,
    daysAgo: 5,
    upvoterIndexes: [0, 4],
    status: 'resolved',
    officerRemark: 'Tree removed by parks department maintenance crew.',
    feedback: { rating: 4, comment: 'Took a few days but got done.' },
  },
  {
    title: 'Noise complaint - construction after hours',
    description: 'A nearby construction site is operating heavy machinery well past permitted hours, disturbing residents at night.',
    category: 'Other',
    area: 'Clifton',
    citizenIndex: 2,
    daysAgo: 12,
    upvoterIndexes: [1],
    status: 'pending',
  },
  {
    title: 'Damaged bus shelter roof',
    description: 'The roof of the public bus shelter is damaged and no longer provides shelter from rain, affecting daily commuters.',
    category: 'Road',
    area: 'Korangi',
    citizenIndex: 3,
    daysAgo: 40,
    upvoterIndexes: [0, 1, 2, 3, 4],
    status: 'resolved',
    officerRemark: 'Shelter roof repaired and repainted.',
    feedback: { rating: 2, comment: 'Took over a month to get fixed.' },
  },
  {
    title: 'Blocked storm drain causing flooding',
    description: 'A blocked storm drain is causing water to pool on the road every time it rains, making the street impassable.',
    category: 'Water',
    area: 'Malir',
    citizenIndex: 4,
    daysAgo: 22,
    upvoterIndexes: [0, 1, 3],
    status: 'in-progress',
    officerRemark: 'Drain cleaning crew scheduled for this week.',
  },
];

module.exports = { officer, citizens, complaintTemplates };
